### ISSUE TITLE
No Issue: Just a big thanks

### ISSUE THREAD

**Issue by m040601** [richin13/tmux-plugin-playerctl#1]
No Issue, just a big thank you for this plugin. 

Got to know about it today here, https://github.com/rothgar/awesome-tmux/pull/81.

Was looking for this kind of functionaliy for a long time. Big fan of mpris and playerctl. Your plugin does the job perfectly. Simple, clean and efficient.

You might just want to add to the README that it requires "bash" and not only "sh" because of "#!/usr/bin/env bash".

Keep up the great work.

**Comment by richin13** [comment]
Hey thank you for your words, I'm really glad you find it useful. I'll update the README 🚀
